# Generated by hand: add xp and level fields to Profile
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_age_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
