# Generated by Django 5.2.7 on 2026-06-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_streak_fields'),
        ('users', '0004_profile_xp_and_level'),
    ]

    operations = [
    ]
